DATABASE_IP = "10.0.10.126"
DATABASE_PORT = "3306"
USER = "admin"
PASSWORD = "Welcome1."
DB_NAME = "cotizar_ms"

DATABASE_URL = f"mysql+pymysql://{USER}:{PASSWORD}@{DATABASE_IP}:{DATABASE_PORT}/{DB_NAME}"
